### ISSUE TITLE
Cannot inline bytecode built with jvm target 1.8 into bytecode that is being built with JVM target 1.6

### ISSUE THREAD

**Issue by bonkin** [sdeleuze/spring-kotlin-fullstack#3]
![screenshot_20181221_144900](https://user-images.githubusercontent.com/17380487/50341557-30fd8180-0530-11e9-9710-db5b5a3fc9c5.png)

This annoying error message occurs in both IntelliJ IDEA 2018.2 and 2018.3. Application still could be successfully run.

**Comment by sdeleuze** [comment]
Can't reproduce
